Warn, don't fail on insecure admin password
The entrypoint no longer insists on a secure admin password to start.
I've added various warnings instead.

The rational is that starting without a password file only occurs if the
compose setup is started either manually, i.e. with docker-compose, or
the handle-instances script.  In both cases the instance will, by
default, listen on localhost only.

The osinstancectl script, which does make instances available to the
internet, will always automatically generate secure passwords.

diff --git a/server/entrypoint b/server/entrypoint
--- a/server/entrypoint
+++ b/server/entrypoint
@@ -9,17 +9,30 @@ wait-for-it --timeout=5 postgres:5432
 echo 'running migrations'
 python manage.py migrate
 
-if [[ ! -f /app/personal_data/admin-password-set ]]; then
-  echo "Retrieving secure admin password"
-  source /run/secrets/os_admin
-  [[ -n "${OPENSLIDES_ADMIN_PASSWORD}" ]] || {
-    echo "ERROR: OpenSlides admin password not set.  Aborting."
-    exit 2
-  }
-  echo 'change admin password'
-  python manage.py insecurechangepassword admin "${OPENSLIDES_ADMIN_PASSWORD}"
-  # Note password change in persistent volume
-  touch /app/personal_data/admin-password-set
+if [[ -f /run/secrets/os_admin ]]; then
+  if [[ ! -f /app/personal_data/admin-password-set ]]; then
+    echo "Retrieving secure admin password"
+    source /run/secrets/os_admin
+    [[ -n "${OPENSLIDES_ADMIN_PASSWORD}" ]] || {
+      echo "ERROR: OpenSlides admin password not set.  Aborting."
+      exit 2
+    }
+    echo 'change admin password'
+    python manage.py insecurechangepassword admin "${OPENSLIDES_ADMIN_PASSWORD}"
+    # Note password change in persistent volume
+    touch /app/personal_data/admin-password-set
+  fi
+else
+  cat <<-EOF
+
+                 ==============================================
+                                    WARNING
+                 ==============================================
+
+                 WARNING: INSECURE ADMIN ACCOUNT CONFIGURATION!
+
+EOF
+  sleep 10
 fi
 
 if [[ -f /run/secrets/os_user ]] && [[ ! -f /app/personal_data/user-added ]]; then
