Create a secure admin user account from the start

diff --git a/server/entrypoint b/server/entrypoint
--- a/server/entrypoint
+++ b/server/entrypoint
@@ -4,10 +4,21 @@
 
 set -e
 
+echo "Retrieving secure admin password"
+source /run/secrets/os_admin
+
+[[ -n "${OPENSLIDES_ADMIN_PASSWORD}" ]] || {
+  echo "ERROR: OpenSlides admin password not set.  Aborting."
+  exit 2
+}
+
 wait-for-it --timeout=5 postgres:5432
 
 echo 'running migrations'
 python manage.py migrate
+
+echo 'change admin password'
+python manage.py insecurechangepassword admin "${OPENSLIDES_ADMIN_PASSWORD}"
 
 echo 'executing server'
 printf 'INFO: Running CMD: "%s".\n' "$*"
